FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu24.04

# Set the working directory
WORKDIR /app

# Copy and install requirements
COPY requirements.cuda.txt ./
RUN pip install --no-cache-dir -r requirements.cuda.txt

# Copy the application code
COPY . .

# Expose the port that the server will run on
EXPOSE 8000

# Set environment variable for the model name
ENV MODEL_NAME="google-bert/bert-base-uncased"

# Run the server
CMD ["python", "-u", "main.py"]